jobs:
  build:
    docker:
      - image: node:12.20.1
      - image: "cimg/python:3.6"

    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      #     - run: yarn test
      - run: yarn build
      - aws-s3/sync:
          arguments: "--delete"
          from: build/
          to: "s3://projectx-frontend"

      - run: yarn webhook-slack
orbs:
  aws-s3: circleci/aws-s3@2.0.0
version: 2.1
